name: Deployment

concurrency:
  group: production
  cancel-in-progress: true

on:
  push:
    branches:
      - $default-branch
  workflow_dispatch:

jobs:
  deployment:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - name: Checkout code
        uses: actions/checkout@v7

      - name: Setup Python & Install MyST
        uses: actions/setup-python@v7
        with:
          python-version: '3.11'
      - name: Install MySTMD
        # https://pypi.org/project/mystmd/
        run: pip install mystmd

      - name: Build Site
        run: |
          myst clean -y
          myst build --html

      - name: Fix Local URLs
        run: |
          grep -Rl "http://localhost:3[0-9]{3}" ./_build/html/ | xargs -r sed -i -E 's|http://localhost:3[0-9]{3}|https://raphael.doursenaud.fr|g' || true

      - name: Deploy via Rsync
        uses: burnett01/rsync-deployments@9.0.1
        with:
          switches: -av --delete
          path: _build/html/
          remote_path: sites/raphael.doursenaud.fr/
          remote_host: ox8ba0.ftp.infomaniak.com
          remote_user: ox8ba0_deploy-gh
          remote_key: ${{ secrets.INFOMANIAK_SSH_KEY }}
